name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ matrix.host }}

    strategy:
      matrix:
        host:
          - lima

    steps:
      - name: Clear Space
        run: sudo rm -rf /usr/share /usr/local || true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: accept-flake-config = true
          # extra_nix_config: | # deploy-rs can't use nixConfig
          #   substituters = https://cache.garnix.io
          #   trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      # - name: Setup TailScale
      #   uses: tailscale/github-action@v2
      #   with:
      #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #     oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
      #     tags: tag:ci

      # - name: Update Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan ${{ matrix.host }} >> ~/.ssh/known_hosts

      - name: Prebuild Script
        run: |
          SCRIPT=systems/x86_64-linux/${{ matrix.host }}/PREBUILD.sh
          if [ -f $SCRIPT ]; then
            $SCRIPT
          fi

      - name: Wait on Checks
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          running-workflow-name: deploy (${{ matrix.host }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prebuild Checks
        if: always()
        run: |
          echo "Memory and swap:"
          sudo free
          echo
          sudo swapon --show
          echo
          echo "Available storage:"
          sudo df -h
          echo "Usage summary:"
          du -h -d 1

      - name: Build & Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        run: |
          nix run github:cachix/cachix deploy activate -a ${{ matrix.host }} "$(nix build --print-out-paths)"

      - name: Postbuild Checks
        if: always()
        run: |
          echo "Memory and swap:"
          sudo free
          echo
          sudo swapon --show
          echo
          echo "Available storage:"
          sudo df -h
          echo "Usage summary:"
          du -h -d 1
