name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ matrix.host }}

    strategy:
      matrix:
        host:
          - lima

    steps:
      - name: Clear Space
        run: sudo rm -rf /usr/share /usr/local /opt || true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: | # deploy-rs won't read nixConfig
            accept-flake-config = true
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Setup TailScale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:deploy

      - name: Setup SSH
        uses: Wandalen/wretry.action@v3.5.0
        with:
          command: | # avoid using magicDNS due to bugs
            mkdir -p ~/.ssh
            ipv4="$(tailscale ip -4 ${{ matrix.host }})"
            ssh-keyscan "$ipv4" >> ~/.ssh/known_hosts
            echo "ipv4=$ipv4" >> "$GITHUB_ENV"

      - name: Activate Shell
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: .#deploy

      - name: Checks...
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore_pattern: deploy \(.+\)

      - name: Build & Deploy
        uses: Wandalen/wretry.action@v3.5.0
        with:
          command: |
            deploy -s --hostname "$ipv4" --ssh-user deploy .#${{ matrix.host }}
