name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ matrix.host }}

    strategy:
      matrix:
        host:
          - lima

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: accept-flake-config = true

      - name: Maximise Space
        uses: easimon/maximize-build-space@v10

      - name: Setup TailScale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Update Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ matrix.host }} >> ~/.ssh/known_hosts

      - name: Prebuild Script
        run: |
          SCRIPT=systems/x86_64-linux/${{ matrix.host }}/PREBUILD.sh
          if [ -f $SCRIPT ]; then
            $SCRIPT
          fi

      - name: Wait on Checks
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          running-workflow-name: deploy (${{ matrix.host }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Deploy
        run: |
          nix run github:serokell/deploy-rs -- .#${{ matrix.host }}
