name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ matrix.host }}

    strategy:
      matrix:
        host:
          - lima

    steps:
      - name: Clear Space
        run: sudo rm -rf /usr/share /usr/local /opt || true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: accept-flake-config = true

      - name: Setup TailScale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Update Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ matrix.host }} >> ~/.ssh/known_hosts

      - name: Run Prebuild
        env:
          script: systems/x86_64-linux/${{ matrix.host }}/PREBUILD.sh
        run: type "$script" && "$script"; true

      - name: Checks
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore_pattern: deploy \(.+\)

      - name: Build & Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        run: |
          nix run github:serokell/deploy-rs -- --skip-checks --hostname=${{ matrix.host }}

      - name: Postbuild Analysis
        if: always()
        run: |
          echo "--- Disk Usage"
          sudo df -h
