name: Diff

# TODO
# Implement home-manager diff using
#   https://discourse.nixos.org/t/viewing-differences-between-flake-revisions/18768/2

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      hosts: ${{ steps.hosts.outputs.hosts }}

    steps:
      - name: Check Previous Deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$(gh api repos/${{ github.repository }}/deployments | jq length)" -gt 1 ]; then
            exit 0
          else
            exit 1
          fi

      - name: List Hosts
        id: hosts
        run: |
          echo 'hosts=["lima"]' >> "$GITHUB_OUTPUT"

  diff:
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        host: ${{ fromJSON(needs.check.outputs.hosts) }}

    steps:
      - name: Clear Space
        run: sudo rm -rf /usr/share /usr/local /opt || true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: accept-flake-config = true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Activate Shell
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: .#deploy

      - name: Get Commit
        id: get_commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo old="$(gh api repos/${{ github.repository }}/deployments | jq -r '.[1].sha')" >> "$GITHUB_OUTPUT"
          echo new="$(gh api repos/${{ github.repository }}/deployments | jq -r '.[0].sha')" >> "$GITHUB_OUTPUT"

      - name: Build NixOS
        uses: Wandalen/wretry.action@v3.5.0
        with:
          command: |
            nix build \
              --out-link old \
              github:${{ github.repository}}/${{ steps.get_commit.outputs.old }}#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel &
            nix build \
              --out-link new \
              github:${{ github.repository}}/${{ steps.get_commit.outputs.new }}#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel &
            wait

      - name: Get Diff
        run: nvd diff old new
