name: Diff

# TODO
# Fix build process running out of space
# Implement home-manager diff using
#   https://discourse.nixos.org/t/viewing-differences-between-flake-revisions/18768/2

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      hosts: ${{ steps.hosts.outputs.hosts }}

    steps:
      - name: Check Previous Deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$(gh api repos/${{ github.repository }}/deployments | jq length)" -gt 1 ]; then
            exit 0
          else
            exit 1
          fi

      - name: List Hosts
        id: hosts
        run: |
          echo 'hosts=["lima"]' >> "$GITHUB_OUTPUT"

  old:
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        host: ${{ fromJSON(needs.check.outputs.hosts) }}

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            accept-flake-config = true
            substituters = https://cache.garnix.io
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Get Commit
        id: get_commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ref="$(gh api repos/${{ github.repository }}/deployments | jq -r '.[1].sha')" >> "$GITHUB_OUTPUT"

      - name: Build NixOS
        run: |
          nix build \
            --out-link new \
            github:${{ github.repository}}/${{ steps.get_commit.outputs.ref }}#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: old
          path: old

  new:
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        host: ${{ fromJSON(needs.check.outputs.hosts) }}

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            accept-flake-config = true
            substituters = https://cache.garnix.io
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Get Commit
        id: get_commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ref="$(gh api repos/${{ github.repository }}/deployments | jq -r '.[0].sha')" >> "$GITHUB_OUTPUT"

      - name: Build NixOS
        run: |
          nix build \
            --out-link new \
            github:${{ github.repository}}/${{ steps.get_commit.outputs.ref }}#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: new
          path: new

  diff:
    runs-on: ubuntu-latest
    needs:
      - check
      - old
      - new

    strategy:
      matrix:
        host: ${{ fromJSON(needs.check.outputs.hosts) }}

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            accept-flake-config = true
            substituters = https://cache.garnix.io
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Use Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Download Results
        uses: actions/download-artifact@v4

      - name: Get Diff
        run: |
          nix run gitlab:khumba/nvd --no-write-lock-file -- \
            diff old new
